### ISSUE TITLE
Nothing pip install random error

### ISSUE THREAD

**Issue by shodiq86** [o0mrferi0o/instagram-brute-forcer#1]

**Comment by MrF3ri** [comment]
hi , 
what is the problem ?

**Comment by brxndonnn** [comment]
Collecting argparse (from -r ./requirements.txt (line 1))
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting logging (from -r ./requirements.txt (line 2))
  Downloading logging-0.4.9.6.tar.gz (96 kB)
     ---------------------------------------- 96.0/96.0 kB 686.3 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\Brandon Roux\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 7, in <module>
          import _distutils_hack.override  # noqa: F401
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Brandon Roux\AppData\Local\Programs\Python\Python311\Lib\site-packages\_distutils_hack\override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "C:\Users\Brandon Roux\AppData\Local\Programs\Python\Python311\Lib\site-packages\_distutils_hack\__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "C:\Users\Brandon Roux\AppData\Local\Programs\Python\Python311\Lib\site-packages\_distutils_hack\__init__.py", line 63, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Brandon Roux\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Brandon Roux\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 22, in <module>
          from .dist import Distribution
        File "C:\Users\Brandon Roux\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 12, in <module>
          import logging
        File "C:\Users\Brandon Roux\AppData\Local\Temp\pip-install-qls17rh0\logging_101d756e71204ad7a81105ca623adc17\logging\__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
